const { project } = require("@utils/projection");
const { http_status, user_type } = require("@enums");
const { user_messages } = require("@validators/messages");
const { send_response, get_response_shape } = require("@helpers/common");
const { signup_response, create_managed_user } = require("@helpers/auth");

/**
 * Creates an employee account.
 *
 * Only an admin may call this. That is enforced on the router by
 * `authenticate_user` followed by `authorize_user_types(ADMIN)`, not here, so
 * the rule is read in one place next to the address it guards.
 *
 * A super admin is deliberately not allowed through. Each group creates the
 * group below it: a super admin makes admins, an admin makes employees. Letting
 * a super admin do both would make the chain a suggestion rather than a rule,
 * and there would then be two paths to the same account with only one of them
 * tested.
 *
 * The new account's group is fixed to `employee` by this file. It is never read
 * from the request, and `employee_signup_schema` refuses a `user_type` field, so an
 * admin cannot send `user_type: "admin"` and create a colleague at their own
 * level.
 *
 * The account starts on the shared default password. The caller has to pass
 * that on to the new employee themselves; this reply does not repeat it,
 * because it is the same for everyone and is not a secret this endpoint is
 * keeping.
 *
 * `emp_id` is generated by the server and is in the reply, since that is the
 * only place the caller can learn it.
 *
 * @route   POST /admin/auth/employee/signup
 * @access  Admin
 *
 * @param   {import("express").Request} req
 * @param   {Object} req.body Validated by `employee_signup_schema`, which rejects
 *                            unknown fields.
 * @param   {string} req.body.first_name   Required. 1-100 chars, trimmed.
 * @param   {string} req.body.last_name    Required. 1-100 chars, trimmed.
 * @param   {string} req.body.email        Required. 5-254 chars, must be a
 *                                         valid email. Stored lower case.
 *                                         Unique.
 * @param   {string} req.body.phone_number Required. Exactly 10 digits. Unique.
 * @param   {string} req.body.username     Required. 3-50 chars. Stored lower
 *                                         case. Unique.
 * @param   {import("express").Response} res
 *
 * @returns {Promise<void>} 201 with the account columns listed in
 *                          `signup_response`.
 *
 * @throws  {app_error} 401 when the caller sent no usable token.
 * @throws  {app_error} 403 `ACCESS_FORBIDDEN` when the caller is not an admin.
 * @throws  {app_error} 409 `ALREADY_EXISTS` when the email, phone number or
 *                      username already belongs to another user.
 * @throws  {app_error} 409 `EMP_ID_SEQUENCE_EXHAUSTED` once 999 accounts exist
 *                      for the current month.
 */
const employee_signup = async (req, res) => {
  const user = await create_managed_user(req.body, user_type.EMPLOYEE);

  const { select } = get_response_shape(signup_response, "create");

  // The document was written rather than fetched, so there was no query to hang
  // the projection on. It is narrowed here instead of being re-read purely to
  // reshape data the process is already holding.
  return send_response(
    res,
    http_status.CREATED,
    user_messages.EMPLOYEE_CREATED,
    project(user, select),
  );
};

module.exports = employee_signup;
