const user_model = require("@models/user_model");

const { project } = require("@utils/projection");
const { http_status, user_type } = require("@enums");
const { user_messages } = require("@validators/messages");
const { emp_id_generation } = require("@validators/constants");
const { retry_when, send_response, get_response_shape } = require("@helpers/common");
const {
  auth_response,
  get_next_emp_id,
  is_emp_id_duplicate_error,
  run_with_user_duplicate_mapping,
} = require("@helpers/auth");

/**
 * Creates a super admin account.
 *
 * Open by design: this is the bootstrap endpoint, so it has to run before any
 * account exists to authorise it. `user_type` is forced to `super_admin` and
 * `emp_id` is generated by the server, so a caller cannot set either.
 *
 * `emp_id` is `YYMM` plus a 3 digit counter that restarts every Indian calendar
 * month, so `2609001` is the first account of September 2026. Two signups at the
 * same instant work out the same id and the unique index rejects one, so the
 * write is retried with a fresh counter up to `emp_id_generation.MAX_ATTEMPTS`
 * times. A duplicate email, phone number or username is the caller's to fix, so
 * it is returned rather than retried.
 *
 * The password is hashed by the model before it is saved. The reply describes
 * the new account but carries no token, because signing up is not signing in.
 *
 * @route   POST /super-admin/auth/signup
 * @access  Public
 *
 * @param   {import("express").Request} req
 * @param   {Object} req.body Validated by `super_admin_signup_schema`, which
 *                            rejects unknown fields.
 * @param   {string} req.body.first_name   Required. 1-100 chars, trimmed.
 * @param   {string} req.body.last_name    Required. 1-100 chars, trimmed.
 * @param   {string} req.body.email        Required. 5-254 chars, must be a valid
 *                                         email. Stored lower case. Unique.
 * @param   {string} req.body.phone_number Required. Exactly 10 digits. Unique.
 * @param   {string} req.body.username     Required. 3-50 chars. Stored lower
 *                                         case. Unique.
 * @param   {string} req.body.password     Required. 8-20 chars. Stored hashed.
 * @param   {import("express").Response} res
 *
 * @returns {Promise<void>} 201 with the account columns listed in
 *                          `auth_response`. No token.
 *
 * @throws  {app_error} 409 `ALREADY_EXISTS` when the email, phone number or
 *                      username already belongs to another user.
 * @throws  {app_error} 409 `EMP_ID_SEQUENCE_EXHAUSTED` once 999 accounts exist
 *                      for the current month.
 */
const super_admin_signup = async (req, res) => {
  // Two concurrent signups read the same "last" emp_id and compute the same
  // next one; the unique index rejects the loser. That clash is the server's
  // own doing, so it is retried with a freshly read sequence rather than handed
  // to a caller who could not have caused it.
  //
  // The duplicate mapping sits outside the retry deliberately. Mapping first
  // would rewrite the emp_id collision into an app_error that
  // `is_emp_id_duplicate_error` no longer recognises, and the retry would never
  // fire. Out here it only ever sees what the retry gave up on -- a clashing
  // email, phone number or username, every one of them the caller's to fix.
  const user = await run_with_user_duplicate_mapping(() =>
    retry_when(
      is_emp_id_duplicate_error,
      emp_id_generation.MAX_ATTEMPTS,
      async () =>
        user_model.create({
          ...req.body,
          emp_id: await get_next_emp_id(),
          user_type: user_type.SUPER_ADMIN,
        }),
    ),
  );

  // The same shape the signin endpoints answer with, minus the token: signing
  // up is not signing in, so the account is described and the caller is left to
  // authenticate. `auth_response` declares no reference to expand, so there is
  // nothing to populate before the projection.
  const { select } = get_response_shape(auth_response, "create");

  // The document was written rather than fetched, so there was no query to hang
  // the projection on. It is narrowed here instead of being re-read purely to
  // reshape data the process is already holding.
  return send_response(
    res,
    http_status.CREATED,
    user_messages.CREATED,
    project(user, select),
  );
};

module.exports = super_admin_signup;
