const joi = require("joi");

const { user_validation_messages } = require("@validators/messages");
const {
  email,
  first_name,
  last_name,
  password,
  phone_number,
  username,
} = require("@validators/request_body/auth/user_fields");

/**
 * The body the super admin signup accepts.
 *
 * Six fields, all required. `emp_id` and `user_type` are absent on purpose: the
 * employee id is generated by the server (`get_next_emp_id` in
 * `@helpers/auth`) and the user type is fixed by the controller, so neither is
 * the caller's to set.
 *
 * Because `unknown(false)` refuses anything it does not name, sending either of
 * them is a 400 rather than a value silently dropped. That is the intent: a
 * caller who tries to choose their own role is told no, not quietly ignored.
 *
 * Every field comes from `user_fields`, so signup and signin cannot disagree
 * about what a valid username or password is.
 *
 * @type {import("joi").ObjectSchema}
 */
const super_admin_signup_schema = joi
  .object({
    first_name,
    last_name,
    email,
    phone_number,
    username,
    password,
  })
  .unknown(false)
  .messages({
    "object.unknown": user_validation_messages.UNKNOWN_FIELD,
  });

module.exports = super_admin_signup_schema;
