const app_error = require("@middlewares/app_error");

const { http_status } = require("@enums");
const { user_messages } = require("@validators/messages");

/**
 * Turns a duplicate key error into a conflict worded for a user account, and
 * returns anything else untouched.
 *
 * A user carries four unique indexes -- email, phone_number, username and
 * emp_id -- and only emp_id is generated by the server. The other three come
 * straight from the caller, so any user write can land on a row that already
 * exists. Unique indexes are database constraints rather than Mongoose
 * validators, so the clash arrives as a bare driver error that the generic
 * handler answers with wording belonging to no entity in particular.
 *
 * The offending column travels in `details` rather than in the message: a caller
 * fixing the request needs to know which field clashed, while one message
 * already covers all four.
 *
 * Anything that is not an 11000, and any 11000 that names no column, is returned
 * as it came so the error handler still classifies it. An 11000 naming nothing
 * is not something a caller can act on, so it is not dressed up as fixable.
 *
 * @param   {Error} error  The error a write threw.
 * @returns {Error|app_error} A 409 `app_error` for a named duplicate, otherwise
 *                            the original error.
 */
const map_user_duplicate_error = (error) => {
  if (error?.code !== 11000) {
    return error;
  }

  // `keyValue` carries the values the driver actually rejected; `keyPattern` is
  // the fallback for the writes that report only the index definition.
  const fields = Object.keys(error.keyValue || error.keyPattern || {});

  if (!fields.length) {
    return error;
  }

  return new app_error(
    http_status.CONFLICT,
    user_messages.ALREADY_EXISTS,
    fields.map((field) => ({
      field,
      message: user_messages.ALREADY_EXISTS,
      type: "duplicate_value",
    })),
  );
};

module.exports = { map_user_duplicate_error };
