const fs = require('node:fs');
const path = require('node:path');

const backfill_config = require('./backfill_config');
const {
  migrations_directory,
  generator_log_file,
  read_pending_migrations,
  read_executed_migrations,
  strip_timestamp,
} = require('../migration_utils');
const { create_logger } = require('../migration_logger');

/**
 * Turns scripts/generator/backfill_config.js into a migration file.
 *
 *   npm run migrate:generate
 *
 * Everything the generator owns lives in this folder: the config you edit, this
 * script, and generator.log recording what was generated and when. The output
 * does not stay here -- a generated file is written into scripts/migrations
 * alongside hand written ones, so there is a single ordered sequence, a single
 * archive, and a single apply/rollback pipeline.
 *
 * The generated file is ordinary code with `up` and `down`, no different from
 * one written by hand -- read it, edit it, delete it. Nothing reads the config
 * again at run time: the targets are baked into the file so an applied
 * migration keeps describing what it actually did, however the config changes
 * afterwards.
 *
 * Generating does not apply anything. Run `npm run migrate` when the file looks
 * right.
 */

const logger = create_logger(generator_log_file);

const validate_config = (config) => {
  if (!Array.isArray(config) || !config.length) {
    throw new Error(
      'scripts/generator/backfill_config.js must export a non-empty array',
    );
  }

  return config.flatMap((entry, entry_index) => {
    const where = `entry ${entry_index + 1}`;

    if (!entry?.collection || typeof entry.collection !== 'string') {
      throw new Error(`${where}: "collection" must be a non-empty string`);
    }

    if (!Array.isArray(entry.fields) || !entry.fields.length) {
      throw new Error(`${where}: "fields" must be a non-empty array`);
    }

    return entry.fields.map((field, field_index) => {
      const field_where = `${where}, field ${field_index + 1}`;

      if (!field?.name || typeof field.name !== 'string') {
        throw new Error(`${field_where}: "name" must be a non-empty string`);
      }

      // `false`, `0` and `null` are all legitimate defaults, so the key has to
      // be present rather than truthy.
      if (!('default' in field)) {
        throw new Error(
          `${field_where}: "default" is required (use null if the field should be set to null)`,
        );
      }

      const default_value = field.default;

      if (typeof default_value === 'function' || default_value === undefined) {
        throw new Error(
          `${field_where}: a computed default cannot be generated, write that migration by hand`,
        );
      }

      if (default_value instanceof Date) {
        throw new Error(
          `${field_where}: a Date default cannot be generated, write that migration by hand`,
        );
      }

      return {
        collection: entry.collection,
        field: field.name,
        default_value,
      };
    });
  });
};

// Continues the 001_, 002_, ... sequence across both pending and applied files.
const next_sequence_number = () => {
  const names = [
    ...read_pending_migrations(),
    ...read_executed_migrations().map(strip_timestamp),
  ];

  const highest = names.reduce((carry, name) => {
    const [, digits] = name.match(/^(\d+)_/) || [];

    return digits ? Math.max(carry, Number(digits)) : carry;
  }, 0);

  return String(highest + 1).padStart(3, '0');
};

const build_migration_source = (migration_name, targets) => `const mongoose = require('mongoose');

const {
  save_backup,
  read_backup,
  clear_backup,
} = require('@scripts/migration_backup');

/**
 * Generated by \`npm run migrate:generate\` from
 * scripts/generator/backfill_config.js.
 *
 * Sets a default on documents written before the field existed. A Mongoose
 * \`default\` only applies when a document is created, so older documents have
 * no key at all and any query filtering on the field skips them.
 *
 * Only documents where the field is missing or null are touched, which makes
 * \`up\` safe to run more than once. The collections are read through the raw
 * driver rather than a model, so no schema validation or \`updated_at\` stamp is
 * applied -- the backfill leaves every other field exactly as it was.
 */

const MIGRATION_NAME = '${migration_name}';

// Frozen at generation time. Editing the config does not change this list.
const targets = ${JSON.stringify(targets, null, 2)};

const missing_field = (field) => ({
  $or: [{ [field]: { $exists: false } }, { [field]: null }],
});

const up = async () => {
  const applied = [];

  for (const target of targets) {
    const collection = mongoose.connection.collection(target.collection);
    const label = \`\${target.collection}.\${target.field}\`;

    const documents = await collection
      .find(missing_field(target.field), { projection: { _id: 1 } })
      .toArray();

    const ids = documents.map((document) => document._id);

    applied.push({
      collection: target.collection,
      field: target.field,
      ids,
    });

    // Recorded before the write: once the field is set these documents are
    // indistinguishable from ones created with it, and a crash mid-update
    // would otherwise leave nothing for \`down\` to work from.
    await save_backup(MIGRATION_NAME, { applied });

    if (!ids.length) {
      console.log(\`  \${label}: nothing to backfill\`);
      continue;
    }

    const result = await collection.updateMany(
      { _id: { $in: ids } },
      { $set: { [target.field]: target.default_value } },
    );

    console.log(\`  \${label}: set on \${result.modifiedCount} of \${ids.length} document(s)\`);
  }
};

const down = async () => {
  const backup = await read_backup(MIGRATION_NAME);

  if (!backup) {
    // Stripping the field from every document holding the default would hit
    // ones written since, so the rollback stops rather than guessing.
    throw new Error(
      \`no backup recorded for \${MIGRATION_NAME}, so the documents it changed cannot be identified\`,
    );
  }

  // Reverse order, so a migration whose targets depend on each other unwinds
  // the way it was applied.
  for (const target of [...backup.applied].reverse()) {
    const label = \`\${target.collection}.\${target.field}\`;

    if (!target.ids.length) {
      console.log(\`  \${label}: nothing to revert\`);
      continue;
    }

    const collection = mongoose.connection.collection(target.collection);

    const result = await collection.updateMany(
      { _id: { $in: target.ids } },
      { $unset: { [target.field]: '' } },
    );

    console.log(
      \`  \${label}: removed from \${result.modifiedCount} of \${target.ids.length} document(s)\`,
    );
  }

  await clear_backup(MIGRATION_NAME);
};

module.exports = { up, down };
`;

const generate = () => {
  const targets = validate_config(backfill_config);
  const migration_name = `${next_sequence_number()}_backfill_defaults`;
  const file_name = `${migration_name}.js`;
  const file_path = path.join(migrations_directory, file_name);

  if (fs.existsSync(file_path)) {
    throw new Error(`${file_name} already exists`);
  }

  // Each target is printed rather than just counted, so the log records the
  // defaults a migration was generated with even if the file is later edited.
  targets.forEach((target) => {
    console.log(
      `  ${target.collection}.${target.field} -> ${JSON.stringify(target.default_value)}`,
    );
  });

  fs.mkdirSync(migrations_directory, { recursive: true });
  fs.writeFileSync(
    file_path,
    build_migration_source(migration_name, targets),
    'utf8',
  );

  return file_name;
};

const run = logger.open_run('generate', null);
const entry = logger.start_entry('GENERATE', 'backfill_config.js');

try {
  const file_name = generate();

  logger.finish_entry(entry, 'OK', `scripts/migrations/${file_name}`);
  logger.close_run(run, `generated ${file_name}`);

  console.log(`Created scripts/migrations/${file_name}`);
  console.log(`Logged to ${logger.log_file}`);
  console.log('Review it, then apply with: npm run migrate');
} catch (error) {
  logger.finish_entry(entry, 'FAILED', error.message);
  logger.close_run(run, 'generated nothing');

  console.error(`Generate failed: ${error.message}`);
  process.exitCode = 1;
}
